from typing import ClassVar
from typing import Protocol

from werkzeug import Response


class IStorage(Protocol):
    separator: ClassVar[str]

    def get_base_path(self) -> str: ...
    def make_dir(self, path: str, directory: str): ...
    def get_files(
        self, path: str, directory: str
    ) -> list[tuple[str, str, bool, int, int]]: ...
    def delete_tree(self, directory: str): ...
    def delete_file(self, file_path: str): ...
    def path_exists(self, path: str) -> bool: ...
    def rename_path(self, src: str, dst: str): ...
    def is_dir(self, path: str) -> bool: ...
    def send_file(self, file_path: str) -> Response: ...
    def read_file(self, path: str) -> bytes: ...
    def write_file(self, path: str, content: str) -> int: ...
    def save_file(self, path: str, file_data: str): ...
